"use server";
import { revalidatePath } from "next/cache";
import { requireAuthorizedAdmin } from "@/lib/auth/adminAuth";
import { generateCertificateId, getCertificateVerificationUrl } from "@/lib/academy/certificates";
import { createSupabaseAdminClient } from "@/lib/supabase/server";
export async function createEnrollment(formData: FormData){ const admin=await requireAuthorizedAdmin(); const s=createSupabaseAdminClient(); if(!s) return; const status=String(formData.get("status")||"active"); await s.from("academy_enrollments").upsert({student_id:String(formData.get("studentId")),course_id:String(formData.get("courseId")),status,access_source:String(formData.get("accessSource")||"admin_grant"),payment_reference:String(formData.get("paymentReference")||"")||null,amount_paid:Number(formData.get("amountPaid")||0)||null,currency:String(formData.get("currency")||"HTG"),validated_by:admin.id,validated_at:["active","completed"].includes(status)?new Date().toISOString():null},{onConflict:"student_id,course_id"}); revalidatePath("/admin/academy/enrollments"); }
export async function createCertificate(formData: FormData){ await requireAuthorizedAdmin(); const s=createSupabaseAdminClient(); if(!s) return; const cert=generateCertificateId(); await s.from("academy_certificates").insert({certificate_id:cert,student_id:String(formData.get("studentId")),course_id:String(formData.get("courseId")),student_full_name:String(formData.get("studentFullName")),course_title:String(formData.get("courseTitle")),verification_url:getCertificateVerificationUrl(cert),status:"issued"}); revalidatePath("/admin/academy/certificates"); }
export async function revokeCertificate(formData: FormData){ await requireAuthorizedAdmin(); const s=createSupabaseAdminClient(); if(!s) return; await s.from("academy_certificates").update({status:"revoked"}).eq("id",String(formData.get("id"))); revalidatePath("/admin/academy/certificates"); }
export async function createCourse(formData: FormData){ await requireAuthorizedAdmin(); const s=createSupabaseAdminClient(); if(!s) return; await s.from("academy_courses").insert({title:String(formData.get("title")),slug:String(formData.get("slug")),category:String(formData.get("category")||"Formation"),short_description:String(formData.get("shortDescription")||""),description:String(formData.get("description")||""),level:String(formData.get("level")||"beginner"),duration:String(formData.get("duration")||""),status:String(formData.get("status")||"draft"),price_amount:Number(formData.get("priceAmount")||0)||null,is_free:formData.get("isFree")==="on",published_at:formData.get("status")==="published"?new Date().toISOString():null}); revalidatePath("/admin/academy/courses"); }
