import { createSupabaseAdminClient, createSupabaseServerClient } from "@/lib/supabase/server";
import type { AcademyCourse, AcademyEnrollment, AcademyLesson, AcademyModule, AcademyResource, LessonProgress } from "@/types/academy";

export async function getPublishedAcademyCourses() { const s=createSupabaseServerClient(); if(!s) return [] as AcademyCourse[]; const {data}=await s.from("academy_courses").select("*").eq("status","published").order("published_at",{ascending:false}); return (data ?? []) as AcademyCourse[]; }
export async function getAcademyCourseBySlug(slug:string) { const s=createSupabaseServerClient(); if(!s) return null; const {data}=await s.from("academy_courses").select("*").eq("slug",slug).eq("status","published").maybeSingle(); return data as AcademyCourse|null; }
export async function getPublicCourseProgram(courseId:string) { const s=createSupabaseServerClient(); if(!s) return {modules:[],lessons:[]}; const [{data:modules},{data:lessons}]=await Promise.all([s.from("academy_modules").select("*").eq("course_id",courseId).eq("status","published").order("position"), s.from("academy_lessons").select("id,course_id,module_id,title,position,is_preview,duration,status").eq("course_id",courseId).eq("status","published").order("position")]); return {modules:(modules??[]) as AcademyModule[], lessons:(lessons??[]) as AcademyLesson[]}; }
export async function hasActiveEnrollment(studentId:string, courseId:string) { const s=createSupabaseAdminClient(); if(!s) return false; const {data}=await s.from("academy_enrollments").select("id,status,expires_at").eq("student_id",studentId).eq("course_id",courseId).in("status",["active","completed"]).maybeSingle(); return Boolean(data && (!data.expires_at || new Date(data.expires_at)>new Date())); }
export async function getStudentCourses(studentId:string) { const s=createSupabaseAdminClient(); if(!s) return [] as AcademyEnrollment[]; const {data}=await s.from("academy_enrollments").select("*, academy_courses(*)").eq("student_id",studentId).order("created_at",{ascending:false}); return (data??[]) as AcademyEnrollment[]; }
export async function getLearningPayload(studentId:string, slug:string) { const s=createSupabaseAdminClient(); if(!s) return null; const {data:course}=await s.from("academy_courses").select("*").eq("slug",slug).maybeSingle(); if(!course) return null; const allowed=await hasActiveEnrollment(studentId, course.id); if(!allowed) return {course:course as AcademyCourse, allowed:false, modules:[], lessons:[], resources:[], progress:[]}; const [{data:modules},{data:lessons},{data:resources},{data:progress}]=await Promise.all([s.from("academy_modules").select("*").eq("course_id",course.id).eq("status","published").order("position"),s.from("academy_lessons").select("*").eq("course_id",course.id).eq("status","published").order("position"),s.from("academy_resources").select("*").eq("course_id",course.id).order("position"),s.from("academy_lesson_progress").select("*").eq("student_id",studentId).eq("course_id",course.id)]); return {course:course as AcademyCourse, allowed:true, modules:(modules??[]) as AcademyModule[], lessons:(lessons??[]) as AcademyLesson[], resources:(resources??[]) as AcademyResource[], progress:(progress??[]) as LessonProgress[]}; }
export function computeProgress(lessons: {id:string}[], progress: LessonProgress[]) { if(!lessons.length) return 0; const done=new Set(progress.filter(p=>p.is_completed).map(p=>p.lesson_id)); return Math.round((lessons.filter(l=>done.has(l.id)).length/lessons.length)*100); }
