alter table public.academy_courses add column if not exists price_amount numeric(12,2), add column if not exists price_currency text default 'HTG', add column if not exists is_free boolean default false;
create table if not exists public.academy_payments (id uuid primary key default gen_random_uuid(), student_id uuid not null references auth.users(id) on delete cascade, course_id uuid not null references public.academy_courses(id) on delete cascade, enrollment_id uuid null references public.academy_enrollments(id) on delete set null, provider text not null check (provider in ('moncash','natcash','mock')), amount numeric(12,2) not null, currency text not null default 'HTG', status text not null default 'pending' check (status in ('pending','processing','paid','failed','cancelled','expired','manual_review')), provider_reference text null, provider_checkout_url text null, provider_payload jsonb not null default '{}'::jsonb, metadata jsonb not null default '{}'::jsonb, paid_at timestamptz null, verified_at timestamptz null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create index if not exists academy_payments_student_idx on public.academy_payments(student_id);
create index if not exists academy_payments_course_idx on public.academy_payments(course_id);
create index if not exists academy_payments_status_idx on public.academy_payments(status);
create index if not exists academy_payments_provider_reference_idx on public.academy_payments(provider_reference);
drop trigger if exists set_academy_payments_updated_at on public.academy_payments; create trigger set_academy_payments_updated_at before update on public.academy_payments for each row execute function public.set_updated_at();
alter table public.academy_payments enable row level security;
drop policy if exists "Students can read own academy payments" on public.academy_payments; create policy "Students can read own academy payments" on public.academy_payments for select to authenticated using (student_id=auth.uid());
